### PR TITLE
Adding a variant of sshPairs that takes arguments for the ssh program.

### PR DESCRIPTION
**Pull request by cgo**
Let me know what you think, I needed that for checking something out on a remote device
with a non-standard SSH port.

### CODE REVIEW

**Comment by gregwebs** [comment]
Thanks! I find that many people miss out on the opportunity to do ssh configuration with ~/.ssh/config. But there will still be cases that need this. Can we find a better name for this than `sshPairs2` ?

**Comment by cgo** [comment]
Hi Greg,
I was wondering about that. I just called it sshPairs2 because I could not think of a better name.
How about sshPairsWithArgs or *WithOptions?

**Comment by gregwebs** [comment]
WithOptions sounds descriptive

**Comment by gregwebs** [comment]
great!

**Pull request merged**
