### PR TITLE
Bump UB on time dependency

### PR DESCRIPTION
**Pull request by relrod**

### CODE REVIEW

**Comment by snoyberg** [comment]
@gregwebs This would definitely help Stackage Nightly: shelly is currently blocking a lot of packages, since c2hs depends on it.

**Comment by bergmark** [comment]
I added a revision for this: https://hackage.haskell.org/package/shelly-1.6.6/revisions/

Please merge this PR anyway so the repo stays up to date.

**Comment by gregwebs** [comment]
Does that mean I should not release this to hackage?

**Comment by bergmark** [comment]
You can, but there's no need to.

**Pull request merged**
