### PR TITLE
Relax directory bound

### PR DESCRIPTION
**Pull request by mpickering**
GHC 8.0.2 ships with directory 1.3.

### CODE REVIEW

**Comment by hvr** [comment]
@mpickering have you reviewed the code to see whether the semantic change in `canonicalizePath` from 1.2->1.3 affects shelly's usage?

**Comment by mpickering** [comment]
I didn't test it at all.

**Comment by domenkozar** [comment]
cc @snoyberg

**Comment by snoyberg** [comment]
@gregwebs Any objection to me merging this?

**Comment by snoyberg** [comment]
Even if I was to merge this, I don't have access to upload/revise on Hackage, that would be either @gregwebs or @jwiegley.

**Comment by jwiegley** [comment]
I don't appear to have merge rights in this repository, so it's down to @gregwebs.

**Comment by hvr** [comment]
@snoyberg before this can be merged responsibly somebody has to review that the semantic change in directory-1.3 doesn't affect shelly's correctness

**Comment by fosskers** [comment]
Fixing the resolver to `lts-8.0` and adding to this PR [this change](https://github.com/k0001/Shelly.hs/commit/32a1e290961755e7b2379f59faa49b13d03dfef6), all tests pass.

**Comment by fosskers** [comment]
Hi, any word on this?

**Comment by gregwebs** [comment]
Sorry for the leave of absence! I will merge this and add some hackage permissions.

**Comment by fosskers** [comment]
`8.0.2` for everybody!

**Pull request merged**
