### PR TITLE
MonadFail support

### PR DESCRIPTION
**Pull request by endgame**
You will need to merge #185 also, and the two together should give you proper GHC8.8 support.

### CODE REVIEW

**Comment by gregwebs** [comment]
This seemed to break GHC < 8. https://travis-ci.org/yesodweb/Shelly.hs/jobs/551518946

**Comment by endgame** [comment]
Looks like the MonadFail instances don't hit `transformers` until `transformers-0.5.0.0`: https://hackage.haskell.org/package/transformers-0.5.6.2/changelog

GHC 7.10.3 (the last <8 release) has `transformers-0.4.2.0`. GHC 7.10.3 was released in 2015; is it still necessary to support?

**Comment by gregwebs** [comment]
I don't think it is necessary. But if its easy to support I would

**Comment by endgame** [comment]
I believe the fix would be to the test suite: putting orphan instances
behind CPP to check MIN_VERSION_transformers.

It doesn't pass my effort:reward tradeoff, but it may pass yours.

**Comment by gregwebs** [comment]
no, does't pass mine either.

**Pull request merged**
