### PR TITLE
Strongly escape SSH commands

### LINKED ISSUE #146: SSH should escape quotes
When nesting commands in an SSH call, quotes should be escaped to not match the outer quotes. For example, running `sshPairs_ "user@example.com" [("cat", "foo bar.txt")]` will raise the exceptions: `foo: No such file or directory` and `bar.txt: No such file or directory` (The exceptions would look different if `foo bar.txt` actually existed, but this still shows the bug).

The only way to escape it is with [`'"'"'`](https://stackoverflow.com/a/1250279/4966649). What I think should happen is in [`sshPairsWithOptions'`](https://hackage.haskell.org/package/shelly-1.6.8.3/docs/src/Shelly.html#line-1065), prepend `toSSH` with `replace "'" "'\"'\"'" $`.

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Fixes #146 

Tested locally. There don't seem to be any SSH tests.

### CODE REVIEW

**Comment by gregwebs** [comment]
Thanks! Any chance of adding a test case, at least here in the comments?

**Comment by brandon-leapyear** [comment]
I don't see how tests can be added, since an SSH test would require some other server to constantly be running to accept SSH connections from tests, right?

The test I ran locally was I had a server at some ip address and then ran `stack ghci` with Shelly. Then I ran (with my changed code)
```
shelly $ sshPairsWithOptions "user@example.com" ["-i", "/path/to/pem"] [("cat", ["foo bar.txt"])]
```
which returned `cat: foo bar.txt: No such file or directory`, when before `foo` and `bar.txt` were parsed separately.

**Comment by brandon-leapyear** [comment]
@gregwebs Any updates to this?

**Comment by gregwebs** [comment]
Let me know if master is working for you

**Comment by qwfy** [comment]
This still fails when the remote command contains `(` (parenthesis).

Reproduce:

    -- in a stack created dir, foo/

    -- file: app/MinRepro.hs
    {-# LANGUAGE OverloadedStrings #-}
    {-# LANGUAGE ExtendedDefaultRules #-}
    {-# OPTIONS_GHC -fno-warn-type-defaults #-}

    import Shelly
    import qualified Data.Text as T
    import qualified System.IO

    default (T.Text)

    main = do
        System.IO.hSetBuffering System.IO.stdout System.IO.LineBuffering
        shelly $ verbosely $ do
          let opts =
                  [ "--some-option", "(7)"
                  ]
          sshPairs_ "<your name>@<your host>" [("true", opts)]


    -- part of file: foo.cabal
    executable min-repro
      hs-source-dirs:      app
      main-is:             MinRepro.hs
      ghc-options:         -O2 -threaded
      build-depends:       base
                         , foo
                         , text
                         , shelly==1.6.9
      default-language:    Haskell2010


    -- part of file: stack.yaml
    packages:
    - .
    - location:
        git: https://github.com/yesodweb/Shelly.hs.git
        commit: f64f1abab1a41ffa10e6e37289adb30d48386200
      extra-dep: true

Then:

    $ stack build
    $ stack exec min-repro

will reports:

    Exception: error running: ssh user@host '"true --some-option (7)"'
    exit status: 1
    stderr: bash: -c: line 0: syntax error near unexpected token `('
    bash: -c: line 0: `true --some-option (7)'

**Comment by brandon-leapyear** [comment]
^ Not sure what you're trying to do, it doesn't seem to be a valid bash command anyway

```
$ true --some-option (7)
-bash: syntax error near unexpected token `('
```

**Comment by gregwebs** [comment]
yeah, not understanding this. Test cases are great (there is a `SshSpec.hs` now.

**Comment by qwfy** [comment]
Maybe I'm having the wrong expectation/understanding, but when I pass a string, say `(7)`, as an argument to a command, in this case, `true`, I expect that `true` sees a literal `(7)`, NOT that the shell sees a literal `(7)`, that is, every funny character should be escaped such that the command (not the shell) would see what I initially passed.

Considering the following code:

    main = do
        System.IO.hSetBuffering System.IO.stdout System.IO.LineBuffering
        let filename = <filename read from else where, like stdin or command line argument>
        shelly $ verbosely $ do
          let opts =
                  [ "--some-option", filename
                  ]
          sshPairs_ "<your name>@<your host>" [("true", opts)]

In the case of the `true --some-option (7)`, you can always try to quote the `(7)` in the code manually, maybe something like `"'(7)'"`, (which is not a good practice I think), but in the above code, the `filename` argument may or may not contain funny characters like spaces and parenthesis, thus the quoting of the filename has to be done by A library in a systematic way.

Also, the behaviour is some what inconsistent, for example (note the last line, it's a `run`)

    main = do
        System.IO.hSetBuffering System.IO.stdout System.IO.LineBuffering
        shelly $ verbosely $ do
          let opts =
                  [ "--some-option", "(7)"
                  ]
          run "true" opts

works ok.

**Comment by gregwebs** [comment]
Ahh, I see. I opened #159 to address that.

**Comment by qwfy** [comment]
@gregwebs Thanks, the response is really fast ;) Unfortunately, this still will not work for argument like `'7` (a more reasonable example: `Andrew's Photos/2017/`). After some digging, I found [how OCaml does this (quote ONE argument)](https://github.com/ocaml/ocaml/blob/caf391ff2ebe90967198d5f2b30a47e7d1f67216/stdlib/filename.ml#L16):

- place an opening single quote `'` at the beginning of a newly created string
- scan the to be quoted string, if a `'` is encountered, append a `'` (terminates the last single quote), append a sh-quoted single quote, `\'`, append a `'` (opens a new single quote)
- finally, append a closing single quote `'`

**Comment by gregwebs** [comment]
Yeah, I definitely know its not perfect now. Can you send a PR with test cases?

**Comment by qwfy** [comment]
#160

**Pull request merged**
